name: velocimetro
description: Aplicativo que funciona como velocímetro e hodômetro usando GPS
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  # Pacote para obter a localização GPS
  geolocator: ^10.0.1
  
  # Pacote para gerenciamento de estado
  provider: ^6.0.5
  
  # Pacotes para UI
  google_fonts: ^6.1.0
  flutter_svg: ^2.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/